---
name: CI

'on':
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: CI/${{ github.repo }}/${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  EARTHLY_CI: 'true'
  FORCE_COLOR: 1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Earthly
        uses: drugscom/setup-earthly-action@v1
      - name: Run CI tests
        run: earthly +test
