---
name: CD

'on':
  workflow_call:

concurrency:
  group: CD-docker-push/${{ github.repo }}/${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  EARTHLY_CI: 'true'
  FORCE_COLOR: 1

jobs:
  docker-push:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Earthly
        uses: drugscom/setup-earthly-action@v1
      - name: Get Docker image tags
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
      - name: Get docker args
        id: docker
        run: echo "::set-output name=args::--IMAGE_NAME='${{ join(fromJSON(steps.metadata.outputs.json).tags, ' ') }}'"
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: earthly --push +docker ${{ steps.docker.outputs.args }}
