---
name: Node.js

'on':
  workflow_call:
    inputs:
      node-version:
        description: Version Spec of the Node.js version to use
        default: '16.x'
        required: false
        type: string
      registry-url:
        description: Package registry to set up for auth
        default: 'https://registry.npmjs.org'
        required: false
        type: string
    secrets:
      npm-auth-token:
        required: true

concurrency:
  group: CD/${{ github.repo }}/${{ github.ref }}

jobs:
  npm-publish:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
      - run: npm ci
      - name: Build package
        run: npm run --if-present build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token }}
