---
name: Node.js

'on':
  workflow_call:

concurrency:
  group: ${{ github.repo }}/${{ github.ref }}

permissions:
  contents: write

jobs:
  reset-version:
    name: Reset package version
    runs-on: ubuntu-latest
    if: startsWith(github.event.label.name, 'release:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Revert "Bump package version" commit
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          git revert --no-edit ':/Bump package version'
          git push
